apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
