apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: {{ .Chart.Name }} 
  clusterIP: None