apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.mysql.replicaCount }}
  serviceName: {{ .Chart.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        ports:
        - name: mysql
          containerPort: 3306
        env:
        {{- range $k, $v := .Values.mysql.secrets }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name }}-secrets
              key: {{ $k }}
        {{- end }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database | quote }}
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 2
      volumes:
      - name: config-map
        configMap:
          name: {{ .Chart.Name }}-configmap

      {{- with .Values.mysql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.mysql.pvc.storageClassName | default "standard" }}
      resources:
        requests:
          storage: {{ .Values.mysql.pvc.storage }}