apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  primary.cnf: |
    [mysqld]
    log-bin=mysql-bin
    binlog_format=ROW
    sync_binlog=1
    gtid_mode=ON
    enforce_gtid_consistency=ON

  replica.cnf: |
    [mysqld]
    relay-log=mysql-relay-bin
    read_only=1
    gtid_mode=ON
    enforce_gtid_consistency=ON

  init.sh: |
{{ .Files.Get "files/init.sh" | indent 4 }}

  replication.sh: |
{{ .Files.Get "files/replication.sh" | indent 4 }}