common:
  namespace: mysql

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  secrets:
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_USER: ""
    MYSQL_PASSWORD: ""

  database: app_db
  replicaCount: 2

  pvc:
    storageClassName: "standard"
    storage: 2Gi

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi

  tolerations:
    - key: "app"
      operator: "Equal"
      value: "mysql"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: app
                operator: In
                values:
                  - mysql

    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                  - "mysql"
          topologyKey: "kubernetes.io/hostname"
