apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.common.namespace }}
data:
  PYTHONUNBUFFERED: "1"
  wait-for-db.py: |
{{ .Files.Get "files/wait-for-db.py" | indent 4 }}